# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 11:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import outfit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('outfit_img', models.ImageField(blank=True, height_field=1080, null=True, upload_to=outfit.models.upload_location, width_field=1080)),
                ('category', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tagged_clothes', models.ManyToManyField(to='cloth.Cloth')),
            ],
        ),
    ]
