# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0002_auto_20170915_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='tagged_clothes',
            field=models.ManyToManyField(blank=True, to='cloth.Cloth'),
        ),
    ]
