# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 11:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outfit', '0003_auto_20170915_1127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outfit',
            name='owner',
        ),
        migrations.AddField(
            model_name='outfit',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='outfit.Outfit'),
        ),
        migrations.AddField(
            model_name='outfit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
