# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0005_remove_outfit_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='link',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
