# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-27 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0006_outfit_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Unisex', 'Unisex')], default='Unisex', max_length=10),
        ),
    ]
