# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-05 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0007_auto_20171127_0508'),
    ]

    operations = [
        migrations.AddField(
            model_name='outfit',
            name='description',
            field=models.CharField(blank=True, max_length=299, null=True),
        ),
    ]
