# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0007_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='outfits',
            field=models.ManyToManyField(related_name='categories', to='outfit.Outfit'),
        ),
    ]
