# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-08 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0008_outfit_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='publish',
            new_name='created_at',
        ),
    ]
