# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-08 10:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfit', '0009_auto_20171208_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfit',
            old_name='created_at',
            new_name='publish',
        ),
    ]
