# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-26 12:27
from __future__ import unicode_literals

import cloth.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cloth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field=1080, null=True, upload_to=cloth.models.upload_location, width_field=1080)),
                ('name', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=10)),
                ('cloth_type', models.CharField(choices=[('ts', 't-shirt'), ('ct', 'coat')], default='1', max_length=9)),
                ('size', models.CharField(max_length=3)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('link', models.CharField(max_length=20)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('which', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cloth.Cloth')),
                ('who', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
