# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-15 12:27
from __future__ import unicode_literals

import cloth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0004_auto_20170915_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='cloth_image',
            field=models.ImageField(blank=True, null=True, upload_to=cloth.models.upload_location),
        ),
    ]
