# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-20 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0006_auto_20170916_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='size',
            field=models.CharField(max_length=12),
        ),
    ]
