# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-20 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0007_auto_20170920_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='color',
            field=models.CharField(max_length=6),
        ),
    ]
