# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-21 09:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0009_auto_20170921_0911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth',
            old_name='name',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='cloth',
            name='updated',
        ),
        migrations.AddField(
            model_name='cloth',
            name='in_wardrobe',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='clothdetail',
            name='publish',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clothdetail',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
