# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-21 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0010_auto_20170921_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothdetail',
            name='detail',
            field=models.TextField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='clothdetail',
            name='brand',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clothdetail',
            name='color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='clothdetail',
            name='delivery_loc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clothdetail',
            name='seasons',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='clothdetail',
            name='sex',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='clothdetail',
            name='size',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
