# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-21 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0012_auto_20170921_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothdetail',
            name='size',
            field=models.CharField(blank=True, choices=[('x3s', 'XXXS'), ('x2s', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('x1l', 'XL'), ('x2l', 'XXL'), ('x3l', 'XXXL')], default='m', max_length=12, null=True),
        ),
    ]
