# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-21 14:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0013_auto_20170921_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clothdetail',
            name='cloth',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='c_detail', to='cloth.Cloth'),
        ),
        migrations.AlterField(
            model_name='clothdetail',
            name='size',
            field=models.CharField(blank=True, choices=[('x3s', 'XXXS'), ('x2s', 'XXS'), ('xs', 'XS'), ('s', 'S'), ('m', 'M'), ('l', 'L'), ('x1l', 'XL'), ('x2l', 'XXL'), ('x3l', 'XXXL')], max_length=12, null=True),
        ),
    ]
