# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0014_auto_20170921_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='big_cloth_type',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('outwear', 'Outwear'), ('etc', 'Accessories')], default='top', max_length=11),
        ),
    ]
