# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-26 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0015_cloth_big_cloth_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='big_cloth_type',
            field=models.CharField(choices=[('t', 'Top'), ('b', 'Bottom'), ('o', 'Outwear'), ('s', 'Shoes'), ('e', 'ETC')], default='top', max_length=11),
        ),
    ]
