# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-28 13:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0018_auto_20170926_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='only_me',
            field=models.BooleanField(default=False),
        ),
    ]
