# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0019_cloth_only_me'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='archieve',
            field=models.BooleanField(default=False),
        ),
    ]
