# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 16:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0020_cloth_archieve'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clothdetail',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='clothdetail',
            name='updated',
        ),
        migrations.AddField(
            model_name='cloth',
            name='publish',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
