# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0021_auto_20170929_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='color',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
