# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-29 16:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0022_cloth_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cloth',
            name='color',
        ),
    ]
