# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 14:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0025_remove_clothdetail_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothdetail',
            old_name='delivery_loc',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='clothdetail',
            name='detail',
        ),
    ]
