# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-26 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0029_auto_20171103_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='big_cloth_type',
            field=models.CharField(blank=True, choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Outwear', 'Outwear'), ('Shoes', 'Shoes'), ('ETC', 'ETC')], default='t', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='cloth_type',
            field=models.CharField(blank=True, default='1', max_length=15, null=True),
        ),
    ]
