# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-04 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0030_auto_20171126_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothdetail',
            name='description',
            field=models.CharField(blank=True, max_length=299, null=True),
        ),
    ]
