# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-05 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloth', '0031_clothdetail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='big_cloth_type',
            field=models.CharField(blank=True, choices=[('Top', 'Top'), ('Bottom', 'Bottom'), ('Outerwear', 'Outerwear'), ('Shoes', 'Shoes'), ('ETC', 'ETC')], default='t', max_length=11, null=True),
        ),
    ]
