# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 15:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='username',
            field=models.TextField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
