# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-09 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.SlugField(max_length=20),
        ),
    ]
