# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-11 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20170908_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, height_field=1080, null=True, upload_to=profiles.models.upload_location, width_field=1080),
        ),
    ]
