# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-21 14:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth',
            field=models.DateField(blank=True, default='1992-07-23', null=True),
        ),
    ]
