# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-22 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20170921_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
