# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-28 04:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='follow',
            name='following',
        ),
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
