# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-16 07:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20170928_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.CharField(default='undefined', max_length=8),
        ),
    ]
