# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-20 05:42
from __future__ import unicode_literals

import category.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('main_img', models.ImageField(blank=True, null=True, upload_to=category.models.upload_location_category)),
                ('detail', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
