# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-20 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_auto_20170920_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='outfits',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='outfit.Outfit'),
        ),
    ]
