# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-19 15:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20170918_1128'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['publish']},
        ),
    ]
