# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-12-12 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_remove_comment_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='publish',
            new_name='created_at',
        ),
    ]
